"""initial_spatial_tables

Revision ID: 00daf7b5d741
Revises: 
Create Date: 2026-03-12 20:38:07.050865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00daf7b5d741'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('sea_areas_geom_geom_idx'), table_name='sea_areas', postgresql_using='gist')
    op.create_index('idx_sea_areas_geom', 'sea_areas', ['geom'], unique=False, postgresql_using='gist')
    op.drop_column('sea_areas', 'min_zoom')
    op.drop_column('sea_areas', 'scalerank')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sea_areas', sa.Column('scalerank', sa.NUMERIC(precision=10, scale=0), autoincrement=False, nullable=True))
    op.add_column('sea_areas', sa.Column('min_zoom', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True))
    op.drop_index('idx_sea_areas_geom', table_name='sea_areas', postgresql_using='gist')
    op.create_index(op.f('sea_areas_geom_geom_idx'), 'sea_areas', ['geom'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###
