"""add_user_id_to_reports

Revision ID: 3cf3dba6709c
Revises: a4cb56abf0e3
Create Date: 2026-03-13 22:53:07.380083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf3dba6709c'
down_revision: Union[str, Sequence[str], None] = 'a4cb56abf0e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fish_reports', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fish_reports', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fish_reports', type_='foreignkey')
    op.drop_column('fish_reports', 'user_id')
    # ### end Alembic commands ###
