"""add_fish_types_table

Revision ID: 52cfcc4913f9
Revises: 3cf3dba6709c
Create Date: 2026-03-13 23:02:50.519249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52cfcc4913f9'
down_revision: Union[str, Sequence[str], None] = '3cf3dba6709c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fish_types',
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fish_types_id'), 'fish_types', ['id'], unique=False)
    op.create_index(op.f('ix_fish_types_slug'), 'fish_types', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fish_types_slug'), table_name='fish_types')
    op.drop_index(op.f('ix_fish_types_id'), table_name='fish_types')
    op.drop_table('fish_types')
    # ### end Alembic commands ###
