"""add_users_table

Revision ID: a4cb56abf0e3
Revises: a3f8c2d1e905
Create Date: 2026-03-13 22:19:31.482852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'a4cb56abf0e3'
down_revision: Union[str, Sequence[str], None] = 'a3f8c2d1e905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=True)
    op.alter_column('sea_areas', 'featurecla',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('sea_areas', 'geom',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               type_=geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'),
               existing_nullable=True)
    op.drop_index(op.f('sea_areas_geom_geom_idx'), table_name='sea_areas', postgresql_using='gist')
    op.create_index('idx_sea_areas_geom', 'sea_areas', ['geom'], unique=False, postgresql_using='gist')
    op.drop_column('sea_areas', 'min_zoom')
    op.drop_column('sea_areas', 'scalerank')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sea_areas', sa.Column('scalerank', sa.NUMERIC(precision=1, scale=0), autoincrement=False, nullable=True))
    op.add_column('sea_areas', sa.Column('min_zoom', sa.NUMERIC(precision=1, scale=0), autoincrement=False, nullable=True))
    op.drop_index('idx_sea_areas_geom', table_name='sea_areas', postgresql_using='gist')
    op.create_index(op.f('sea_areas_geom_geom_idx'), 'sea_areas', ['geom'], unique=False, postgresql_using='gist')
    op.alter_column('sea_areas', 'geom',
               existing_type=geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'),
               type_=geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               existing_nullable=True)
    op.alter_column('sea_areas', 'featurecla',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
