"""add social and sos models

Revision ID: f34f5f822807
Revises: eab25da28e60
Create Date: 2026-03-16 23:00:49.807263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f34f5f822807'
down_revision: Union[str, Sequence[str], None] = 'eab25da28e60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sos_alarms',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sos_alarms_id'), 'sos_alarms', ['id'], unique=False)
    op.create_table('fish_report_comments',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['fish_reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fish_report_comments_id'), 'fish_report_comments', ['id'], unique=False)
    op.create_table('fish_report_likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['fish_reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fish_report_likes_id'), 'fish_report_likes', ['id'], unique=False)
    op.drop_index(op.f('idx_land_areas_geom'), table_name='land_areas', postgresql_using='gist')
    op.drop_index(op.f('land_areas_temp_geom_geom_idx'), table_name='land_areas', postgresql_using='gist')
    op.drop_table('land_areas')
    op.add_column('sea_areas', sa.Column('featurecla', sa.String(length=32), nullable=True))
    op.drop_index(op.f('sea_areas_geom_geom_idx'), table_name='sea_areas', postgresql_using='gist')
    op.create_index('idx_sea_areas_geom', 'sea_areas', ['geom'], unique=False, postgresql_using='gist')
    op.drop_column('sea_areas', 'name')
    op.drop_column('sea_areas', 'fclass')
    op.drop_column('sea_areas', 'code')
    op.drop_column('sea_areas', 'osm_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sea_areas', sa.Column('osm_id', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
    op.add_column('sea_areas', sa.Column('code', sa.NUMERIC(precision=4, scale=0), autoincrement=False, nullable=True))
    op.add_column('sea_areas', sa.Column('fclass', sa.VARCHAR(length=28), autoincrement=False, nullable=True))
    op.add_column('sea_areas', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index('idx_sea_areas_geom', table_name='sea_areas', postgresql_using='gist')
    op.create_index(op.f('sea_areas_geom_geom_idx'), 'sea_areas', ['geom'], unique=False, postgresql_using='gist')
    op.drop_column('sea_areas', 'featurecla')
    op.create_table('land_areas',
    sa.Column('ogc_fid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shapename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shapeiso', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shapeid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shapegroup', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shapetype', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ogc_fid', name=op.f('land_areas_temp_pkey'))
    )
    op.create_index(op.f('land_areas_temp_geom_geom_idx'), 'land_areas', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('idx_land_areas_geom'), 'land_areas', ['geom'], unique=False, postgresql_using='gist')
    op.drop_index(op.f('ix_fish_report_likes_id'), table_name='fish_report_likes')
    op.drop_table('fish_report_likes')
    op.drop_index(op.f('ix_fish_report_comments_id'), table_name='fish_report_comments')
    op.drop_table('fish_report_comments')
    op.drop_index(op.f('ix_sos_alarms_id'), table_name='sos_alarms')
    op.drop_table('sos_alarms')
    # ### end Alembic commands ###
