"""add_fish_reports_table

Revision ID: f9b11a23b067
Revises: 00daf7b5d741
Create Date: 2026-03-12 20:43:22.265685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'f9b11a23b067'
down_revision: Union[str, Sequence[str], None] = '00daf7b5d741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fish_reports',
    sa.Column('fish_type_id', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fish_reports_fish_type_id'), 'fish_reports', ['fish_type_id'], unique=False)
    op.create_index(op.f('ix_fish_reports_id'), 'fish_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fish_reports_id'), table_name='fish_reports')
    op.drop_index(op.f('ix_fish_reports_fish_type_id'), table_name='fish_reports')
    op.drop_table('fish_reports')
    # ### end Alembic commands ###
