from geoalchemy2 import Geometry
from sqlalchemy import Column, String, Integer
from database import Base

class SeaArea(Base):
    __tablename__ = "sea_areas"
    
    # ogr2ogr sets 'ogc_fid' as the default primary key, replacing 'id'
    ogc_fid = Column(Integer, primary_key=True)
    
    # Shapefile columns:
    featurecla = Column(String(32), nullable=True)
    
    # The geometry column generated by POSTGIS + ogr2ogr (-lco GEOMETRY_NAME=geom)
    geom = Column(Geometry(geometry_type='MULTIPOLYGON', srid=4326))

    class Config:
        arbitrary_types_allowed = True